version: '3.7'

services:
  xenforo_server:
    build:
      context: ./.docker/
      dockerfile: xf2-php-fpm.dockerfile
    container_name: xenforo
    healthcheck:
      test: ["CMD", "php-fpm-healthcheck"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 1m
    networks:
      - xenforo
    restart: always
    working_dir: /var/www/html
    volumes:
      - xenforo-data:/var/www/html
    environment:
      DB_PORT: 3306
      DB_HOST: xenforo-db
      DB_USER: xenforo
      DB_PASSWORD: EcF7T7UGkH4mPGrHDKzwaJjQ
      DB_NAME: xenforo

  nginx:
    image: nginx:1.19-alpine
    container_name: xenforo-nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 1m
    networks:
      - xenforo
    ports:
      - 80:80
    volumes_from:
      - xenforo_server
    volumes:
      - xenforo-nginx-conf:/etc/nginx/conf.d/

  database:
    container_name: xenforo-db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "$MYSQL_USER", "--password=$MYSQL_PASSWORD"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 1m
    networks:
      - xenforo
    image: mariadb:10.3
    volumes:
      - xenforo-database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: xenforo
      MYSQL_USER: xenforo
      MYSQL_PASSWORD: EcF7T7UGkH4mPGrHDKzwaJjQ
      MYSQL_ROOT_PASSWORD: hkRAFzkhwFW7RP52rA54XhBBJvDz

volumes:
  xenforo-database:
  xenforo-data:
    driver_opts:
      type: none
      o: bind
      device: ./
  xenforo-nginx-conf:
    driver_opts:
      type: none
      o: bind
      device: ./.docker/nginx/

networks:
  xenforo:
    name: xenforo
